{% set version = "3.5" %}

package:
  name: x265
  version: {{ version }}

source:
  url: https://bitbucket.org/multicoreware/x265_git/downloads/x265_{{ version }}.tar.gz
  sha256: e70a3335cacacbba0b3a20ec6fecd6783932288ebc8163ad74bcc9606477cae8

build:
  number: 2
  skip: True  # [win]
  run_exports:
    # 2022/03/01 hmaarrfk
    # Seems lik the SO name changes every minor version
    # https://abi-laboratory.pro/index.php?view=timeline&l=x265
    - {{ pin_subpackage('x265', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - nasm
    - make

test:
  commands:
    - test -f ${PREFIX}/lib/libx265${SHLIB_EXT}
    - test -f ${PREFIX}/lib/pkgconfig/x265.pc
    - test -f ${PREFIX}/include/x265.h
    - x265 --version  # [build_platform == target_platform]
    - x265 --version 2>&1 | grep "8bit"  # [build_platform == target_platform]
    - x265 --version 2>&1 | grep "8bit+10bit+12bit"  # [build_platform == target_platform and (x86_64 or arm64)]

about:
  home: https://www.x265.org/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: 'Open Source H.265/HEVC video encoder'
  description: |
    x265 is a H.265 / HEVC video encoder application library, designed to encode
    video or images into an H.265 / HEVC encoded bitstream.
  dev_url: https://bitbucket.org/multicoreware/x265_git
  doc_url: https://x265.readthedocs.io/

extra:
  recipe-maintainers:
    - matthiasdiener
