{% set version = "3.5" %}

package:
  name: x265
  version: {{ version }}

source:
  url: https://bitbucket.org/multicoreware/x265_git/downloads/x265_{{ version }}.tar.gz
  sha256: e70a3335cacacbba0b3a20ec6fecd6783932288ebc8163ad74bcc9606477cae8
  patches:
    - patches/0001-remove-unsupported-compiler-options-from-arm.patch
    - patches/0002-add-rpath-for-hdr10plus-shared.patch
    - patches/0003-do-not-look-for-strtok_r-on-win.patch
    - patches/0004-force-10-12-bit-build-on-aarch64.patch

build:
  # Missing nasm for s390x
  skip: True  # [s390x]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - nasm  # [x86]
    - make  # [not win]
    - patch     # [not win]
    - m2-patch  # [win]
    # Upstream is using git in cmake to detect source version and configure the build process
    - git  # [not win]

test:
  commands:
    - test -f ${PREFIX}/lib/libx265${SHLIB_EXT}  # [unix]
    - test ! -f ${PREFIX}/lib/libx265.a          # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/x265.pc    # [unix]
    - test -f ${PREFIX}/include/x265.h           # [unix]
    - if not exist %LIBRARY_PREFIX%\include\x265.h exit 1         # [win]
    - if not exist %LIBRARY_PREFIX%\lib\pkgconfig\x265.pc exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\libx265.lib exit 1        # [win]
    - if not exist %LIBRARY_PREFIX%\bin\libx265.dll exit 1        # [win]
    # Make sure not to install static libraries
    - if not exist %LIBRARY_PREFIX%\lib\x265-static.lib exit 1        # [win]
    - x265 --version
    - x265 --version 2>&1 | grep "8bit+10bit+12bit"

about:
  home: https://www.x265.org/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: 'Open Source H.265/HEVC video encoder'
  description: |
    x265 is a H.265 / HEVC video encoder application library, designed to encode
    video or images into an H.265 / HEVC encoded bitstream.
  dev_url: https://bitbucket.org/multicoreware/x265_git
  doc_url: https://x265.readthedocs.io/

extra:
  recipe-maintainers:
    - matthiasdiener
  skip-lints:
    - invalid_url